# Generated by Django 4.2 on 2023-04-29 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="audio",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="books_audio/%Y/%m/%d/",
                verbose_name="Audiosi",
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="download_count",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Yuklab olishlar soni"
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="books_file/%Y/%m/%d/",
                verbose_name="Fayli",
            ),
        ),
    ]
